---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-205
  region: us-east-1
  version: "1.26"

vpc:
  id: "vpc-0a1a7aefd384efa01"
  subnets:
    public:
      my-public-205-a:
        id: "subnet-0b32a3a5a67000ef6"
        az: "us-east-1a"
      my-public-205-b:
        id: "subnet-0f1499d0a0bda4133"
        az: "us-east-1b"
    private:
      my-private-205-a:
        id: "subnet-0d61a727e7a6168b4"
        az: "us-east-1a"
      my-private-205-b:
        id: "subnet-0ea41bdacecf40669"
        az: "us-east-1b"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Disable

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels: { aws-usage: "cluster-ops" }
      wellKnownPolicies:
        autoScaler: true

nodeGroups:
  - name: pvt-205-a-1
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-eks-205: "shared"
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    privateNetworking: true
    subnets:
      - my-private-205-a
  - name: pub-205-a-1
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-eks-205: "shared"
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 0
    minSize: 0
    maxSize: 1
    subnets:
      - my-public-205-a
  - name: pub-205-a-1-taint
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-eks-205: "shared"
    taints:
      - key: nodegroup
        value: pub-205-a-1-taint
        effect: NoSchedule
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    subnets:
    - my-public-205-a