apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-08c8f865a556c6a9a
    fsType: ext4
